---
# tasks file for ubuntu24-clamav
- name: Check OS version and family
  ansible.builtin.fail:
    msg: "This role can only be run against Ubuntu 24. {{ ansible_facts.distribution }} {{ ansible_facts.distribution_major_version }} is not supported."
  when:
    - ansible_facts.distribution == 'Ubuntu'
    - ansible_facts.distribution_major_version is version_compare('24', '!=')
  tags:
    - always

- name: "Run update_cache"
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: "{{ updates_cache_valid_time }}"
  tags:
    - always

- name: "Install packages"
  ansible.builtin.apt:
    pkg: "{{ clamav_packages }}"
  tags:
    - always

- name: "Settings for ClamAV daemon"
  vars:
    package1: 'clamav'
    package2: 'clamav-daemon'
  ansible.builtin.template:
    src: clamd.conf.j2
    dest: "{{ clamd_conf_path }}"
    mode: '0644'
    owner: root
    group: root
  when: (package1 in clamav_packages) or
        (package2 in clamav_packages)
  notify: Restart clamav-daemon service
  tags:
    - always

- name: "Settings for ClamAV Freshclam"
  vars:
    package: 'clamav-freshclam'
  ansible.builtin.template:
    src: freshclam.conf.j2
    dest: "{{ freshclam_conf_path }}"
    mode: '0444'
    owner: clamav
    group: adm
  when: package in clamav_packages
  notify: Restart clamav-freshclam service
  tags:
    - always

...
