name: Scorecard supply-chain security

on:
  branch_protection_rule:
  schedule:
    - cron: '35 23 * * 5'
  push:
    branches:
      - 'main'

permissions:
  contents: read

jobs:
  scorecard:
    permissions:
      actions: read
      contents: read
      security-events: write
      id-token: write
    uses: dafneb/.github/.github/workflows/scorecard.yml@dfac396edbb994866c84cc5a8f7b3812ed3d9ff9
    secrets: inherit
